from building import *

cwd = GetCurrentDir()
src = Glob('*.c')

CPPPATH = [cwd, str(Dir('#'))]

group = DefineGroup('BoardDriver', src, depend = ['RT_USING_DFS'], CPPPATH = CPPPATH)

Return('group')
