# RT-Thread building script for bridge

from building import *

cwd      = GetCurrentDir()
src      = Glob('*.c')

CPPPATH  = [cwd]

group = DefineGroup('agile_modbus\slave', src, depend = ['PKG_USING_AGILE_MODBUS'], CPPPATH = CPPPATH)

Return('group')
