from building import *

cwd = GetCurrentDir()
src = Glob('*.c')
src += Glob('README.md')
CPPPATH = [cwd, str(Dir('#'))]

group = DefineGroup('BoardDriver', src, depend = [''], CPPPATH = CPPPATH)

Return('group')
